### ISSUE TITLE
Using library in PHITS

### ISSUE THREAD

**Issue by Mahdi-20** [highness-eu/NJOY-NCrystal-Library#1]
Hello,
I am trying to use the tsl data (Standard ACE format) for Fe in PHITS code to see the Bragg edges. However, an unknown error ocuures saying the internal file format has a problem.
I was wondering if this ACE format can be used in PHITS or just they can be used in MNCP?
Thanks in advance. 
Mahdi

**Comment by marquezj** [comment]
Hi @Mahdi-20. You need to use a recent version of PHITS (3.28a and up) in order to use the data libraries in this repository.

**Comment by Mahdi-20** [comment]
Dear @marquezj ,
Thank you for your comment.
I will ask for the new version of PHITS and will check it. Then report here if it works.

**Comment by Mahdi-20** [comment]
Dear @marquezj,
I installed PHITS-3.28a and I used the following material section in my input file.

M1 
26054.50c    # JENDL-4.0
26055.50c
26056.50c
26057.50c
26058.50c
mt1 Fe-038.00t            #using tsl for alpha-Iron

However, the same error occurred as  `forrtl: server (64): input conversion error, unit -5, file Internal Formatted Read`

Am I missing something that I get such an error?

Thanks.
Mahdi

**Comment by marquezj** [comment]
Hi @Mahdi-20 what precise steps did you follow to install the library in your PHITS installation? Please make sure that you:

- Downloaded the binary files from Github (either by cloning the repo or downloading the raw file).
- Uncompressed the ACE files using xz.
- Added the appropriate xsdir file to your PHITS configuration.

**Comment by Mahdi-20** [comment]
Dear @marquezj,
I found a missing `0` in the xsdir that I defined for this library. Thank you for bringing that to my attention.
Now it is working !

PHITS itself has a function to simulate the elastic scattering for cold neutrons for only Alpha iron.
I have compared PHITS built-in function with that of TSL NJOY+Ncrystal in the figure below. The results are very consistent. I showed the gamma iron just for comparison as well.

![image](https://user-images.githubusercontent.com/90252318/177548122-4e009715-7f6a-4562-856f-8e26cf159a87.png)

Thank you again for your comments.
Mahdi

**Comment by henrykline9-droid** [comment]
> Dear [@marquezj](https://github.com/marquezj), I found a missing `0` in the xsdir that I defined for this library. Thank you for bringing that to my attention. Now it is working !
> 
> PHITS itself has a function to simulate the elastic scattering for cold neutrons for only Alpha iron. I have compared PHITS built-in function with that of TSL NJOY+Ncrystal in the figure below. The results are very consistent. I showed the gamma iron just for comparison as well.
> 
> ![image](https://user-images.githubusercontent.com/90252318/177548122-4e009715-7f6a-4562-856f-8e26cf159a87.png)
> 
> Thank you again for your comments. Mahdi

How do you use NJOY+Ncrystal in PHITs? In your opinion, do you need to use this library for using crystals as moderators, or is PHITs elastic scattering sufficient enough?
