### ISSUE TITLE
gamma-Fe TSL

### ISSUE THREAD

**Issue by Mahdi-20** [highness-eu/NJOY-NCrystal-Library#2]
Dear experts, 
I am trying to generate the TSL for gammaFe at 293 K using leapr in NJOY21. 
However, some options in the leapr input files do not work for my NJOY code such as iel=99. 
I have attached snapshots of some errors I faced:

![image](https://user-images.githubusercontent.com/90252318/220497443-1d4de1e3-72ad-4ec8-a42b-0c59060be778.png)

And after deleting -600.00

![image](https://user-images.githubusercontent.com/90252318/220496974-7c280b07-f825-49b8-814c-ebab7c5364eb.png)

Is there any way to solve this issue? 

Thank you.
Mahdi

**Comment by water-L** [comment]
It seems you use a wrong version of NJOY-NCRYSTAL. If you download the tool from "https://github.com/highness-eu/NJOY2016.git", change the branch to "njoy_ncrystal" may work(●'◡'●)
